[book]
authors = ["Gabriel Hansson <gabrielhansson00@gmail.com>"]
language = "en"
src = "book"
title = "`rops` Documentation"

[rust]
edition = "2021"

[build]
build-dir = "target/book"

[preprocessor.cmdrun]

[output.html]
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/gibbz00/rops"
edit-url-template = "https://github.com/gibbz00/rops/edit/main/{path}"
cname = "gibbz00.github.io"
