name: Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish_book:
      name: Publish mdBook
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Checkout sources
          uses: actions/checkout@v6
        - name: Build setup
          uses: ./.github/actions/build_setup
        - name: mdBook setup
          uses: ./.github/actions/book_setup
        - name: Build book
          run: mdbook build
        - name: Deploy to GitHub pages
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: target/book
            git-config-email: <>
  publish_crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Build setup
        uses: ./.github/actions/build_setup
      - name: Publish rops library
        run: cargo publish --package rops
      - name: Publish rops cli
        run: cargo publish --package rops-cli
